{% set version = "2.0.5" %}

package:
  name: async-lru
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/async_lru/async_lru-{{ version }}.tar.gz
  sha256: 481d52ccdd27275f42c43a928b4a50c3bfb2d67af4e78b170e3e0bb39c66e5bb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.0.0

test:
  source_files:
    - tests
  imports:
    - async_lru
  commands:
    - pip check
    - mypy -m async_lru
    - pytest -vv --asyncio-mode=auto --cov=async_lru --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=89
  requires:
    - mypy
    - pip
    - pytest-asyncio
    - pytest-cov
    - python {{ python_min }}

about:
  home: https://github.com/aio-libs/async-lru
  summary: Simple lru_cache for asyncio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
