# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.0.5

package:
  name: async-lru
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/async_lru/async_lru-${{ version }}.tar.gz
  sha256: 481d52ccdd27275f42c43a928b4a50c3bfb2d67af4e78b170e3e0bb39c66e5bb

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - typing_extensions >=4.0.0

tests:
  - python:
      imports: async_lru
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - tests/
    requirements:
      run:
        - mypy
        - pytest-asyncio
        - pytest-cov
        - python ${{ python_min }}
    script:
      - coverage run --source=async_lru -m pytest -vv --asyncio-mode=auto --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=89
      - mypy -m async_lru

about:
  summary: Simple lru_cache for asyncio
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/aio-libs/async-lru

extra:
  recipe-maintainers:
    - bollwyvl
